comment-summary-in-pr: always
fail_on_severity: 'critical'
allow_licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'Apache-2.0'
  - 'PSF-2.0'
  - 'ISC'
  - 'HPND'
  - 'CC0-1.0'
  - '0BSD'
  - 'PSF-2.0'
  - 'Python-2.0'
  - 'WTFPL'
  - 'LGPL-3.0'
  - 'Apache-2.0 AND MIT'
  - 'MIT AND Zlib'
  - 'BSD-3-Clause AND BSD-3-Clause-Clear'
  - 'ISC AND MIT'
  - 'Unlicense'
